version: '3'
services:
  rule-meister:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app:rw,cached
      - /app/node_modules
    environment:
      - TZ=Asia/Tokyo
      - BOT_USERNAME=RuleMeister
      - BOT_TOKEN=YOURTOKEN
      - BOT_OWNER_ID=49237546764337152
      - BOT_COMMAND_PREFIX=?rules
      - AUTHORIZED_ROLES=Admin,Mod
      - TYPEORM_DATABASE=db/db.sqlite3
